In [3]:
import glob
import os
import gc
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import joblib
import tqdm
import DER

In [6]:
folder = r"results"
simulations_files = glob.glob(os.path.join(folder, "*.gz"))
res = []
for simulation_file in tqdm.tqdm(simulations_files):
    s = joblib.load(simulation_file)
    res.append({
        'Scenario': os.path.basename(simulation_file).replace(".gz",""),
        'Initial Number of All Customers': sum([l.number_of_active_customers[0] for l in s.lses if "Residential" in l.name]),
        'Initial Number of High-Income Customers': sum([l.number_of_active_customers[0] for l in s.lses if "High_Income" in l.name]),
        'Initial Number of Low-Income Customers': sum([l.number_of_active_customers[0] for l in s.lses if "Low_Income" in l.name]),
        'Final Number of All Customers': sum([l.number_of_active_customers[-1] for l in s.lses if "Residential" in l.name]),
        'Final Number of High-Income Customers': sum([l.number_of_active_customers[-1] for l in s.lses if "High_Income" in l.name]),
        'Final Number of Low-Income Customers': sum([l.number_of_active_customers[-1] for l in s.lses if "Low_Income" in l.name]),
    })
    del s
    gc.collect()
res = pd.DataFrame(res)
res['% Drop All Customers'] = (res['Initial Number of All Customers'] - res['Final Number of All Customers']) / res['Initial Number of All Customers']
res['% Drop High-Income Customers'] = (res['Initial Number of High-Income Customers'] - res['Final Number of High-Income Customers']) / res['Initial Number of High-Income Customers']
res['% Drop Low-Income Customers'] = (res['Initial Number of Low-Income Customers'] - res['Final Number of Low-Income Customers']) / res['Initial Number of Low-Income Customers']
res.to_clipboard(index=False)
res

100%|██████████| 10/10 [00:39<00:00,  3.91s/it]

,Scenario,Initial Number of All Customers,Initial Number of High-Income Customers,Initial Number of Low-Income Customers,Final Number of All Customers,Final Number of High-Income Customers,Final Number of Low-Income Customers,% Drop All Customers,% Drop High-Income Customers,% Drop Low-Income Customers
0,r_once_reb_0_sun_4,1376621.0,163452.0,1213169.0,1057106.0,117397.0,939709.0,0.232101,0.281765,0.225410
1,r_once_reb_26(All)_sun_4,1376621.0,163452.0,1213169.0,859654.0,95056.0,764598.0,0.375533,0.418447,0.369751
2,r_once_reb_26(PV)_sun_4,1376621.0,163452.0,1213169.0,973059.0,107707.0,865352.0,0.293154,0.341048,0.286701
3,r_once_reb_26(PV)_sun_4_no_decom,1376621.0,163452.0,1213169.0,1004223.0,111939.0,892284.0,0.270516,0.315157,0.264501
4,r_once_reb_26(PV)_sun_7,1376621.0,163452.0,1213169.0,855207.0,94587.0,760620.0,0.378764,0.421316,0.373030
5,r_reg_reb_0_sun_4,1376621.0,163452.0,1213169.0,1045383.0,116059.0,929324.0,0.240617,0.289951,0.233970
6,r_reg_reb_26(All)_sun_4,1376621.0,163452.0,1213169.0,852317.0,94243.0,758074.0,0.380863,0.423421,0.375129
7,r_reg_reb_26(PV)_sun_4,1376621.0,163452.0,1213169.0,961904.0,106437.0,855467.0,0.301257,0.348818,0.294849
8,r_reg_reb_26(PV)_sun_4_no_decom,1376621.0,163452.0,1213169.0,1009787.0,112547.0,897240.0,0.266474,0.311437,0.260416
9,r_reg_reb_26(PV)_sun_7,1376621.0,163452.0,1213169.0,847727.0,93779.0,753948.0,0.384197,0.426260,0.378530

In [8]:
folder = r"results"
simulations_files = glob.glob(os.path.join(folder, "*.gz"))
res = []
for simulation_file in tqdm.tqdm(simulations_files):
    s = joblib.load(simulation_file)
    res.append({
        'Scenario': os.path.basename(simulation_file).replace(".gz",""),
        'Initial Number of All Customers': sum([l.number_of_active_customers[0] for l in s.lses if "Residential" in l.name]),
        'Initial Number of High-Income Customers': sum([l.number_of_active_customers[0] for l in s.lses if "High_Income" in l.name]),
        'Initial Number of Low-Income Customers': sum([l.number_of_active_customers[0] for l in s.lses if "Low_Income" in l.name]),
        'Final Number of All Customers': sum([l.number_of_active_customers[-1] for l in s.lses if "Residential" in l.name]),
        'Final Number of High-Income Customers': sum([l.number_of_active_customers[-1] for l in s.lses if "High_Income" in l.name]),
        'Final Number of Low-Income Customers': sum([l.number_of_active_customers[-1] for l in s.lses if "Low_Income" in l.name]),
    })
    del s
    gc.collect()
res = pd.DataFrame(res)
res['% Drop All Customers'] = (res['Initial Number of All Customers'] - res['Final Number of All Customers']) / res['Initial Number of All Customers']
res['% Drop High-Income Customers'] = (res['Initial Number of High-Income Customers'] - res['Final Number of High-Income Customers']) / res['Initial Number of High-Income Customers']
res['% Drop Low-Income Customers'] = (res['Initial Number of Low-Income Customers'] - res['Final Number of Low-Income Customers']) / res['Initial Number of Low-Income Customers']
res.to_clipboard(index=False)
res

100%|██████████| 10/10 [00:39<00:00,  3.91s/it]

,Scenario,Initial Number of All Customers,Initial Number of High-Income Customers,Initial Number of Low-Income Customers,Final Number of All Customers,Final Number of High-Income Customers,Final Number of Low-Income Customers,% Drop All Customers,% Drop High-Income Customers,% Drop Low-Income Customers
0,r_once_reb_0_sun_4,1376621.0,163452.0,1213169.0,1057106.0,117397.0,939709.0,0.232101,0.281765,0.225410
1,r_once_reb_26(All)_sun_4,1376621.0,163452.0,1213169.0,859654.0,95056.0,764598.0,0.375533,0.418447,0.369751
2,r_once_reb_26(PV)_sun_4,1376621.0,163452.0,1213169.0,973059.0,107707.0,865352.0,0.293154,0.341048,0.286701
3,r_once_reb_26(PV)_sun_4_no_decom,1376621.0,163452.0,1213169.0,1004223.0,111939.0,892284.0,0.270516,0.315157,0.264501
4,r_once_reb_26(PV)_sun_7,1376621.0,163452.0,1213169.0,855207.0,94587.0,760620.0,0.378764,0.421316,0.373030
5,r_reg_reb_0_sun_4,1376621.0,163452.0,1213169.0,1045383.0,116059.0,929324.0,0.240617,0.289951,0.233970
6,r_reg_reb_26(All)_sun_4,1376621.0,163452.0,1213169.0,852317.0,94243.0,758074.0,0.380863,0.423421,0.375129
7,r_reg_reb_26(PV)_sun_4,1376621.0,163452.0,1213169.0,961904.0,106437.0,855467.0,0.301257,0.348818,0.294849
8,r_reg_reb_26(PV)_sun_4_no_decom,1376621.0,163452.0,1213169.0,1009787.0,112547.0,897240.0,0.266474,0.311437,0.260416
9,r_reg_reb_26(PV)_sun_7,1376621.0,163452.0,1213169.0,847727.0,93779.0,753948.0,0.384197,0.426260,0.378530